version: "3.7"
services:
  server:
    env_file:
      - .env
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
      args:
        - NODE_PORT=${NODE_PORT}
    ports:
      - 9000:${NODE_PORT}
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo:4.4.2
    ports:
      - 27018:27017
