# docker-compose.yml
#
version: "3.7"
services:
  server:
    container_name: processing-server
    restart: always
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8000"
    env_file:
      - .env
    volumes:
      - ./server:/usr/src/app
      - /usr/src/app/node_modules
    links:
      - mongo
    depends_on:
      - mongo
    command: npm start
  mongo:
    container_name: processing-database
    image: mongo:4.4.2
    ports:
      - "27018:27017"
    volumes: 
      - ./data:/data/db
