# docker-compose.yml
version: "3.7"
services:
  server:
    container_name: ${APP_NAME}-server
    env_file: .env
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - NODE_IMAGE_VERSION=${NODE_IMAGE_VERSION}
        - NODE_PORT=${NODE_PORT}
        - NODE_PORT_INSPECTOR=${NODE_PORT_INSPECTOR}
    depends_on:
      - postgres
    ports:
      - "${NODE_PORT}:${NODE_PORT}"
      - "${NODE_PORT_INSPECTOR}:${NODE_PORT_INSPECTOR}"
    volumes: 
      - ./backend:/home/app/
      - /home/app/node_modules
  postgres:
    container_name: ${APP_NAME}-database
    image: postgres:${POSTGRES_IMAGE_VERSION}
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
